name: flimer
description: Flutter plugin for picking images on Mobile, Desktop and Web.
version: 0.0.1
homepage: https://github.com/eyro-labs/flimer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.2
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.4+1
  file_selector_windows: ^0.0.2+1
  file_selector_linux: ^0.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
