name: flimer
description: Flutter plugin for picking images on Mobile, Desktop and Web.
version: 1.0.2
homepage: https://github.com/eyro-labs/flimer

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cross_file: ^0.3.3+2
  image_picker: ^0.8.6
  image_picker_platform_interface: ^2.6.2
  file_selector: ^0.9.2+2
  file_selector_platform_interface: ^2.4.0
  file_selector_macos: ^0.9.0+4
  file_selector_windows: ^0.9.1+4
  file_selector_linux: ^0.9.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.mesosfer.flimer
        pluginClass: FlimerPlugin
      ios:
        pluginClass: FlimerPlugin
      web:
        pluginClass: FlimerHtml
        fileName: flimer_html.dart
      macos:
        dartPluginClass: Flimer
        pluginClass: none
      windows:
        dartPluginClass: Flimer
        pluginClass: none
      linux:
        dartPluginClass: Flimer
        pluginClass: none
