name: flimer
description: Flutter plugin for picking images on Mobile, Desktop and Web.
version: 1.0.0
homepage: https://github.com/GianSandoval5/flimer

environment:
  sdk: ^3.8.0
  flutter: ^2.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cross_file: ^0.3.4+2
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.1
  file_selector: ^1.0.3
  file_selector_platform_interface: ^2.6.2
  file_selector_macos: ^0.9.4+3
  file_selector_windows: ^0.9.3+4
  file_selector_linux: ^0.9.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gs.flimer
        pluginClass: FlimerPlugin
      ios:
        pluginClass: FlimerPlugin
      web:
        pluginClass: FlimerHtml
        fileName: flimer_html.dart
      macos:
        dartPluginClass: Flimer
        pluginClass: none
      windows:
        dartPluginClass: Flimer
        pluginClass: none
      linux:
        dartPluginClass: Flimer
        pluginClass: none
